name: 'Push'
on: 
  - push
  - workflow_dispatch


jobs:
  build:
    runs-on: 'ubuntu-latest'
    environment: dev

    steps:
    - uses: 'actions/checkout@v1'

    - name: 'Test'
      run: 'echo env: ${{ env.VAR_1 }} - var: ${{ vars.VAR_1 }} -  sec: ${{ env.SECRET_1 }}'

    # - name: 'Build'
    #   run: 'docker build -t myapp .'
    # - name: 'Push'
    #   run: 'docker push myapp'
